Specify C++11
Prompted by an r-hub failure on Debian Linux, R-devel, GCC ASAN/UBSAN

#> g++ -fsanitize=undefined,bounds-strict -fno-omit-frame-pointer -std=gnu++98 -I"/usr/local/lib/R/include" -DNDEBUG -Iunix -I. -Irapidxml -DRCPP_DEFAULT_INCLUDE_CALL=false -I'/home/docker/R/progress/include' -I'/home/docker/R/Rcpp/include' -I/usr/local/include -fvisibility=hidden -fpic -g -O2 -Wall -pedantic -mtune=native -c XlsWorkBook.cpp -o XlsWorkBook.o
#> In file included from /usr/include/c++/10/cstdint:35,
#> from ./libxls/xlstypes.h:44,
#> from libxls/xls.h:42,
#> from XlsWorkBook.h:5,
#> from XlsWorkBook.cpp:3:
#> /usr/include/c++/10/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#> 32 | #error This file requires compiler and library support \
#> | ^~~~~
#> make: *** [/usr/local/lib/R/etc/Makeconf:177: XlsWorkBook.o] Error 1
#> ERROR: compilation failed for package ‘readxl’