Update to libxls 1.6.2 (#658)
* Ingest libxls v1.6.2 4482400

Straight up copying files

* Tweak paths; remake unix/config.h

* Experiment re: locale.h

* Revert "Experiment re: locale.h"

This reverts commit 72eb15b11a07365e17f5446135c5645b222ada64.

* More path tweaks

* Tweak config.h to work on ubuntu and macOS

* Changes to build on Windows

* Initialize the locale

* Separate maintainer and computer generated concerns in unix/config.h

* Use const in declaration of iconv

* Quotes seem more appropriate here

* Mask illegal function for R CMD check

I analyzed which files include which others and determined that inclusion here covers everything we need.

* Include libxls version in DESCRIPTION; update notes

* Add NEWS bullet re: libxls

* Only use the mingw workaround if GCC is <= 4.9.3

As this is the older RTools35 toolchain, and the code works like normal
with the Rtools40 toolchain.

* Specify C++11

Prompted by an r-hub failure on Debian Linux, R-devel, GCC ASAN/UBSAN

#> g++ -fsanitize=undefined,bounds-strict -fno-omit-frame-pointer -std=gnu++98 -I"/usr/local/lib/R/include" -DNDEBUG -Iunix -I. -Irapidxml -DRCPP_DEFAULT_INCLUDE_CALL=false -I'/home/docker/R/progress/include' -I'/home/docker/R/Rcpp/include' -I/usr/local/include -fvisibility=hidden -fpic -g -O2 -Wall -pedantic -mtune=native -c XlsWorkBook.cpp -o XlsWorkBook.o
#> In file included from /usr/include/c++/10/cstdint:35,
#> from ./libxls/xlstypes.h:44,
#> from libxls/xls.h:42,
#> from XlsWorkBook.h:5,
#> from XlsWorkBook.cpp:3:
#> /usr/include/c++/10/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#> 32 | #error This file requires compiler and library support \
#> | ^~~~~
#> make: *** [/usr/local/lib/R/etc/Makeconf:177: XlsWorkBook.o] Error 1
#> ERROR: compilation failed for package ‘readxl’

* Let's go back to where we started!

* Ingest libxls v1.6.2 4482400

Straight up copying files

* Adapt paths to our layout

* Adapt to the new files around locales

* Mask functions that are illegal for R CMD check

* Regenerate windows/config.h

* Regenerate unix/config*

* Workaround locale issues with older Windows toolchain

* Use C++11

* Update NEWS

Co-authored-by: Jim Hester <james.f.hester@gmail.com>